In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip install SpeechRecognition
!pip install google-cloud-speech pandas
!pip install pydub
!apt install ffmpeg
!pip install FER

**Video to Audio and transcription**

In [ ]:
import moviepy.editor as mp
import speech_recognition as sr
from pydub import AudioSegment
import os
import pandas as pd

def video_to_audio(video_path, audio_path):
    """Convert video file to audio file."""
    video = mp.VideoFileClip(video_path)
    video.audio.write_audiofile(audio_path)

def get_audio_length(file_path):
    """Return the length of the audio file in seconds."""
    audio = AudioSegment.from_file(file_path)
    return len(audio) / 1000.0  # Convert milliseconds to seconds

def transcribe_audio_speech_recognition(audio_file_path):
    """Transcribe the given local audio file using the speech_recognition library."""
    recognizer = sr.Recognizer()
    with sr.AudioFile(audio_file_path) as source:
        audio_data = recognizer.record(source)
        try:
            transcript = recognizer.recognize_google(audio_data, language="ur-PK")
            return transcript
        except sr.UnknownValueError:
            print("Google Speech Recognition could not understand the audio")
            return None
        except sr.RequestError as e:
            print(f"Could not request results from Google Speech Recognition service; {e}")
            return None

def read_words_from_file(file_path):
    """Read words from a file and return them as a list."""
    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            return [line.strip().lower() for line in file.readlines()]
    except FileNotFoundError:
        print(f"File not found: {file_path}")
        return []
    except Exception as e:
        print(f"Error reading file {file_path}: {e}")
        return []

# Convert video to audio
video_file_path = '/content/drive/MyDrive/work2/Test/Video/1.mp4'
audio_file_path = '/content/drive/MyDrive/work2/Test/Audio/1.wav'
video_to_audio(video_file_path, audio_file_path)

# Get audio length
length_in_seconds = get_audio_length(audio_file_path)
print(f"The length of the audio file is {length_in_seconds} seconds.")

# Transcribe audio
transcript = transcribe_audio_speech_recognition(audio_file_path)
if transcript:
    print("Transcript:", transcript)
    words_in_transcript = transcript.split()
    transcript_length = len(words_in_transcript)
    print(f"Transcript Length (in words): {transcript_length}")

    # Read positive and negative words from files
    negative_words = read_words_from_file('/content/drive/MyDrive/work2/dictionary/urdu_negative_words.txt')
    positive_words = read_words_from_file('/content/drive/MyDrive/work2/dictionary/urdu_positive_words.txt')

    results = []
    negative_count, positive_count = 0, 0
    for index, word in enumerate(words_in_transcript):
        position = (index + 1) / transcript_length * length_in_seconds
        if word.lower() in negative_words:
            negative_count += 1
            results.append({'Word': word, 'Type': 'Negative', 'Position': index + 1, 'Time': round(position)})
        elif word.lower() in positive_words:
            positive_count += 1
            results.append({'Word': word, 'Type': 'Positive', 'Position': index + 1, 'Time': round(position)})

    # Create DataFrame and display results
    df = pd.DataFrame(results)
    print(df)
    print(f"Total Negative Words: {negative_count}")
    print(f"Total Positive Words: {positive_count}")
else:
    print("No transcript available.")

MoviePy - Writing audio in /content/drive/MyDrive/work2/Test/Audio/1.wav

MoviePy - Done.
The length of the audio file is 164.93 seconds.
Transcript: ٹینشن پاور ہے یعنی پڑھتے وقت وہ جتنا اپنے اندر سماؤ سکتے ہیں وہ بظاہر دیکھنے میں تو 10 گھنٹے مسلسل پڑھتے رہے لیکن ایکچولی اسکی ریٹینشن پاور بہت کم ہوتی ہے وہ جو کچھ ہورہا ہوتا ہے وہ سرفس کے اوپر ہو رہا ہوتا ہے اور ریٹینشن پاور کم ہوتی ہے بہرحال یہ جو ائیس ہے یہ جوں ہی اس کو لیا جاتا ہے تو تین چار پاف کے اندر ہی اپنا اثر کرنا شروع کر دیتی ہے اور دو تین منٹ کے بعد اس کا اثر ہونا شروع ہو جاتا ہے اور اس کا اثر یہ ہوتا ہے کہ ہماری باڈی کے اندر جو پورا دماغ کا کیمیکل سسٹم ہے وہ ڈسٹرب ہو جاتا ہے ہماری باڈی میں ایک سسٹم ہے جو کہ ایک کیمیکل پروڈیوس کرتا ہے اسے ڈوپامین کہتے ہیں دوپہ مین ہمارا پلیجر کا ہارمون ہے اور ہمارا ریوارڈ کا ہارمون ہے اور ڈوپامین تب پروڈیوس ہوتا ہے کہ جب کوئی بھی چیز اپ کو پلے کردے اور جب بھی کوئی ایڈکشن ہوتی ہے تو اس میں ڈوپامین پروڈیوس ہوتا ہے اور ڈوپامین سے ادمی بڑا اچھا محسوس کرتا ہے سینس اف ویل بینگ میں ہوتا ہے وہ سمجھتا ہے کہ میں بہت کانفیڈنس کے ساتھ بات کر رہا ہوں اور میرا الرٹس زیادہ ہوگئی ہے لیکن خطرناک بات یہ ہوتی ہے کہ جو ڈوپامین کے ریسپٹرز ہیں یہ وقت گزرنے کے ساتھ ساتھ ان فلیٹ ہونا شروع ہو جاتے ہیں لہذا ایک پف سے جو اپ کی کیفیت ہوگی اگلی دفعہ وہ 4:00 کے ساتھ ہوگی اس کے بعد پھر اپ کی ڈیوریشن کو کم ہوتی جائے گی اور پھر اپ اہستہ اہستہ اس کے عادی ہو جائیں گے ایک اور خطرناک بات یہ ہے کہ شروع میں اس کے استعمال کرنے والے کو لگتا ہی نہیں ہے کہ میں نشہ کر رہا ہوں اس لئے کہ اس کو تو یہ لگتا ہے کہ میں بہت الرٹ ہو گیا ہوں اس کو تو یہ لگتا ہے میں بہت بہتر ہو گیا ہوں اس کو تو لگتا ہے کہ میں تو بہت خوش ہو گیا لیکن کچھ عرصے کے بعد اہستہ اہستہ پھر اس کے وہ اثرات ہونا شروع ہو جاتے ہیں جن میں سب سے اہم یہ ہے کہ اس کے اندر سائکیٹرک چینجز انا شروع ہوجاتی ہیں یعنی اگر کوئی استعمال نہیں کرے گا تو اس دوران میں اس کو عجیب قسم کے خیالات انا شروع ہو جائیں گے جن میں سب سے خطرناک ہیں پیرا نائی خیالات پیران کا مطلب یہ ہوتا ہے کہ اس کے ذہن میں خیال اجائے گا کہ یہ شخص مجھے مارنا چاہتا ہے یہ شخص میرے خلاف ہو گیا ہے یہ شخص میرا دشمن ہو گیا اور اپ اندازہ کر سکتے ہیں کہ اگر ہمارے دماغ میں اس طرح کی رئیلیٹی سے ہٹ کر فالس خیالات انا شروع ہو جائیں تو ہمارا پورا نفسیاتی مزاج جو ہے وہ بہت تبدیل ہو جائے گا اور اپ نے پھر اس میں بہت عجیب حرکتیں کر سکتا ہے اور پھر جب اپ اس کے ودرول ہوتے ہیں اگر کسی وجہ سے یہ نہ ملے کیونکہ یہ ڈرگ ہے تھوڑی سی مقدار میں کسی کے نکل ائے تو اس کے اوپر وہ جیل میں جا سکتا ہے تو جب وہ اس کو نہ ملے تو پھر اس کو بے خوابی شروع ہو جاتی ہے پھر اس کو نیند نہیں اتی اور جب نیند پوری نہ ہو تو اپ چو چڑھا ہو جائے
Transcript Length (in words): 561
       Word      Type  Position  Time
0      پاور  Positive         2     1
1     مسلسل  Negative        21     6
2      لیکن  Negative        24     7
3      پاور  Positive        28     8
4        کم  Negative        30     9
5      اوپر  Positive        42    12
6      پاور  Positive        49    14
7        کم  Negative        50    15
8       اثر  Negative        74    22
9       اثر  Negative        88    26
10      اثر  Negative        97    29
11   کیمیکل  Negative       110    32
12   کیمیکل  Negative       127    37
13      چیز  Negative       158    46
14   ایڈکشن  Negative       167    49
15     اچھا  Positive       182    54
16    زیادہ  Negative       209    61
17     لیکن  Negative       212    62
18   خطرناک  Negative       213    63
19     دفعہ  Negative       247    73
20       کم  Negative       261    77
21     عادی  Negative       272    80
22   خطرناک  Negative       278    82
23     نہیں  Negative       293    86
24      نشہ  Negative       297    87
25     بہتر  Positive       325    96
26      خوش  Negative       338    99
27     لیکن  Negative       341   100
28      اہم  Positive       362   106
29     نہیں  Negative       379   111
30     عجیب  Negative       388   114
31      قسم  Positive       389   114
32   خطرناک  Negative       401   118
33     دشمن  Negative       437   128
34     فالس  Negative       458   135
35  نفسیاتی  Negative       467   137
36     مزاج  Negative       468   138
37     عجیب  Negative       484   142
38       نہ  Negative       503   148
39     اوپر  Positive       520   153
40      جیل  Negative       522   153
41       نہ  Negative       532   156
42     نہیں  Negative       548   161
43       نہ  Negative       554   163
Total Negative Words: 35
Total Positive Words: 9

**Audio transcription**

In [ ]:
import speech_recognition as sr
from pydub import AudioSegment
import os
import pandas as pd

def get_audio_length(file_path):
    """Return the length of the audio file in seconds."""
    audio = AudioSegment.from_file(file_path)
    return len(audio) / 1000.0  # Convert milliseconds to seconds

def transcribe_audio_speech_recognition(audio_file_path):
    """Transcribe the given local audio file using the speech_recognition library."""
    recognizer = sr.Recognizer()
    with sr.AudioFile(audio_file_path) as source:
        audio_data = recognizer.record(source)
        try:
            transcript = recognizer.recognize_google(audio_data, language="ur-PK")
            return transcript
        except sr.UnknownValueError:
            print("Google Speech Recognition could not understand the audio")
            return None
        except sr.RequestError as e:
            print(f"Could not request results from Google Speech Recognition service; {e}")
            return None

def read_words_from_file(file_path):
    """Read words from a file and return them as a list."""
    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            return [line.strip().lower() for line in file.readlines()]
    except FileNotFoundError:
        print(f"File not found: {file_path}")
        return []
    except Exception as e:
        print(f"Error reading file {file_path}: {e}")
        return []

audio_file_path = '/content/drive/MyDrive/work2/Test/Audio/1.wav'
length_in_seconds = get_audio_length(audio_file_path)
print(f"The length of the audio file is {length_in_seconds} seconds.")

transcript = transcribe_audio_speech_recognition(audio_file_path)
if transcript:
    print("Transcript:", transcript)
    words_in_transcript = transcript.split()
    transcript_length = len(words_in_transcript)
    print(f"Transcript Length (in words): {transcript_length}")

    negative_words = read_words_from_file('/content/drive/MyDrive/work2/dictionary/urdu_negative_words.txt')
    positive_words = read_words_from_file('/content/drive/MyDrive/work2/dictionary/urdu_positive_words.txt')

    results37 = []
    negative_count, positive_count = 0, 0
    negative_positions, positive_positions = [], []  # Lists to store positions

    for index, word in enumerate(words_in_transcript):
        position = (index+1) / transcript_length * length_in_seconds
        if word.lower() in negative_words:
            negative_count += 1
            negative_positions.append(round(position))  # Append to negative_positions list
            # results.append({'Word': word, 'Type': 'Negative', 'Position': index+1, 'Time': round(position)})
        elif word.lower() in positive_words:
            positive_count += 1
            positive_positions.append(round(position))  # Append to positive_positions list
            # results.append({'Word': word, 'Type': 'Positive', 'Position': index+1, 'Time': round(position)})

    print(f"Total Negative Words: {negative_count}")
    print(f"Total Positive Words: {positive_count}")
    print("Negative Word Positions:", negative_positions)
    print("Positive Word Positions:", positive_positions)

    results37.append({'Length': length_in_seconds, 'audio_name': os.path.basename(audio_file_path),'Transcript' : transcript , 'negative_count': negative_count, 'positive_count': positive_count, 'negative_positions' : negative_positions, 'positive_positions': positive_positions})
    # Create DataFrame
    df = pd.DataFrame(results37)

    # Save results to a CSV file
    csv_file_path = '/content/drive/MyDrive/work2/Test/Transcriptions/1.csv'
    df.to_csv(csv_file_path, index=False)
    print(f"Results saved to {csv_file_path}")



else:
    print("No transcript available.")

The length of the audio file is 164.93 seconds.
Transcript: ٹینشن پاور ہے یعنی پڑھتے وقت وہ جتنا اپنے اندر سماؤ سکتے ہیں وہ بظاہر دیکھنے میں تو 10 گھنٹے مسلسل پڑھتے رہے لیکن ایکچولی اسکی ریٹینشن پاور بہت کم ہوتی ہے وہ جو کچھ ہورہا ہوتا ہے وہ سرفس کے اوپر ہو رہا ہوتا ہے اور ریٹینشن پاور کم ہوتی ہے بہرحال یہ جو ائیس ہے یہ جوں ہی اس کو لیا جاتا ہے تو تین چار پاف کے اندر ہی اپنا اثر کرنا شروع کر دیتی ہے اور دو تین منٹ کے بعد اس کا اثر ہونا شروع ہو جاتا ہے اور اس کا اثر یہ ہوتا ہے کہ ہماری باڈی کے اندر جو پورا دماغ کا کیمیکل سسٹم ہے وہ ڈسٹرب ہو جاتا ہے ہماری باڈی میں ایک سسٹم ہے جو کہ ایک کیمیکل پروڈیوس کرتا ہے اسے ڈوپامین کہتے ہیں دوپہ مین ہمارا پلیجر کا ہارمون ہے اور ہمارا ریوارڈ کا ہارمون ہے اور ڈوپامین تب پروڈیوس ہوتا ہے کہ جب کوئی بھی چیز اپ کو پلے کردے اور جب بھی کوئی ایڈکشن ہوتی ہے تو اس میں ڈوپامین پروڈیوس ہوتا ہے اور ڈوپامین سے ادمی بڑا اچھا محسوس کرتا ہے سینس اف ویل بینگ میں ہوتا ہے وہ سمجھتا ہے کہ میں بہت کانفیڈنس کے ساتھ بات کر رہا ہوں اور میرا الرٹس زیادہ ہوگئی ہے لیکن خطرناک بات یہ ہوتی ہے کہ جو ڈوپامین کے ریسپٹرز ہیں یہ وقت گزرنے کے ساتھ ساتھ ان فلیٹ ہونا شروع ہو جاتے ہیں لہذا ایک پف سے جو اپ کی کیفیت ہوگی اگلی دفعہ وہ 4:00 کے ساتھ ہوگی اس کے بعد پھر اپ کی ڈیوریشن کو کم ہوتی جائے گی اور پھر اپ اہستہ اہستہ اس کے عادی ہو جائیں گے ایک اور خطرناک بات یہ ہے کہ شروع میں اس کے استعمال کرنے والے کو لگتا ہی نہیں ہے کہ میں نشہ کر رہا ہوں اس لئے کہ اس کو تو یہ لگتا ہے کہ میں بہت الرٹ ہو گیا ہوں اس کو تو یہ لگتا ہے میں بہت بہتر ہو گیا ہوں اس کو تو لگتا ہے کہ میں تو بہت خوش ہو گیا لیکن کچھ عرصے کے بعد اہستہ اہستہ پھر اس کے وہ اثرات ہونا شروع ہو جاتے ہیں جن میں سب سے اہم یہ ہے کہ اس کے اندر سائکیٹرک چینجز انا شروع ہوجاتی ہیں یعنی اگر کوئی استعمال نہیں کرے گا تو اس دوران میں اس کو عجیب قسم کے خیالات انا شروع ہو جائیں گے جن میں سب سے خطرناک ہیں پیرا نائی خیالات پیران کا مطلب یہ ہوتا ہے کہ اس کے ذہن میں خیال اجائے گا کہ یہ شخص مجھے مارنا چاہتا ہے یہ شخص میرے خلاف ہو گیا ہے یہ شخص میرا دشمن ہو گیا اور اپ اندازہ کر سکتے ہیں کہ اگر ہمارے دماغ میں اس طرح کی رئیلیٹی سے ہٹ کر فالس خیالات انا شروع ہو جائیں تو ہمارا پورا نفسیاتی مزاج جو ہے وہ بہت تبدیل ہو جائے گا اور اپ نے پھر اس میں بہت عجیب حرکتیں کر سکتا ہے اور پھر جب اپ اس کے ودرول ہوتے ہیں اگر کسی وجہ سے یہ نہ ملے کیونکہ یہ ڈرگ ہے تھوڑی سی مقدار میں کسی کے نکل ائے تو اس کے اوپر وہ جیل میں جا سکتا ہے تو جب وہ اس کو نہ ملے تو پھر اس کو بے خوابی شروع ہو جاتی ہے پھر اس کو نیند نہیں اتی اور جب نیند پوری نہ ہو تو اپ چو چڑھا ہو جائے
Transcript Length (in words): 561
Total Negative Words: 35
Total Positive Words: 9
Negative Word Positions: [6, 7, 9, 15, 22, 26, 29, 32, 37, 46, 49, 61, 62, 63, 73, 77, 80, 82, 86, 87, 99, 100, 111, 114, 118, 128, 135, 137, 138, 142, 148, 153, 156, 161, 163]
Positive Word Positions: [1, 8, 12, 14, 54, 96, 106, 114, 153]
Results saved to /content/drive/MyDrive/work2/Test/Transcriptions/1.csv

In [ ]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/work2/Test/Transcriptions/1.csv')
df.head()

,Length,audio_name,Transcript,negative_count,positive_count,negative_positions,positive_positions
0,164.93,1.wav,ٹینشن پاور ہے یعنی پڑھتے وقت وہ جتنا اپنے اندر...,35,9,"[6, 7, 9, 15, 22, 26, 29, 32, 37, 46, 49, 61, ...","[1, 8, 12, 14, 54, 96, 106, 114, 153]"

**Extracted All Frames**

In [ ]:
import cv2
import pandas as pd
import os

# Function to extract frames at each second
def extract_frames_per_second(video_file_path, output_folder):
    video_name = os.path.basename(video_file_path).split('.')[0]
    cap = cv2.VideoCapture(video_file_path)
    frame_info = []
    frame_rate = cap.get(cv2.CAP_PROP_FPS)
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    duration = int(total_frames / frame_rate)  # Total duration in seconds

    for current_time in range(duration):
        cap.set(cv2.CAP_PROP_POS_MSEC, current_time * 1000)
        ret, frame = cap.read()
        if not ret:
            break
        frame_filename = os.path.join(output_folder, f'{video_name}_frame_{current_time}.jpg')
        cv2.imwrite(frame_filename, frame)
        frame_info.append({'Video Name': video_name, 'Frame Path': frame_filename, 'Time in Seconds': current_time})

    cap.release()
    return frame_info

# Directory containing validation videos
validation_video_directory = '/content/drive/MyDrive/work2/Test/Video'
validation_output_base_folder = '/content/drive/MyDrive/work2/Test/All_Frames'

all_frame_info = []  # Store info for all frames from all videos

# Process each video file
video_files = sorted(os.listdir(validation_video_directory))
for video_file in video_files:
    video_file_path = os.path.join(validation_video_directory, video_file)
    video_name = os.path.splitext(video_file)[0]

    # Create output folder for this video
    output_folder = os.path.join(validation_output_base_folder, video_name)
    os.makedirs(output_folder, exist_ok=True)

    # Extract frames at each second
    frame_info = extract_frames_per_second(video_file_path, output_folder)
    all_frame_info.extend(frame_info)

# Save frame information to a new CSV file
frames_csv_path = '/content/drive/MyDrive/work2/Test/Extracted_All_Frames_Path.csv'
frame_info_df = pd.DataFrame(all_frame_info)
frame_info_df.to_csv(frames_csv_path, index=False)

print("Frames extracted and saved.")
print(f"Frame information saved to {frames_csv_path}")

Frames extracted and saved.
Frame information saved to /content/drive/MyDrive/work2/Test/Extracted_All_Frames_Path.csv

In [24]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/work2/Test/Extracted_All_Frames_Path.csv')
df.head()

,Video Name,Frame Path,Time in Seconds
0,1,/content/drive/MyDrive/work2/Test/All_Frames/1...,0
1,1,/content/drive/MyDrive/work2/Test/All_Frames/1...,1
2,1,/content/drive/MyDrive/work2/Test/All_Frames/1...,2
3,1,/content/drive/MyDrive/work2/Test/All_Frames/1...,3
4,1,/content/drive/MyDrive/work2/Test/All_Frames/1...,4

In [25]:

import pandas as pd

csv_file_path = '/content/drive/MyDrive/work2/Test/Extracted_Key_Frames_Info.csv'

df = pd.read_csv(csv_file_path)
df.head()

,Video Name,Frame Path,Time in Seconds
0,1,/content/drive/MyDrive/work2/Test/Key_Frames/1...,0
1,1,/content/drive/MyDrive/work2/Test/Key_Frames/1...,6
2,1,/content/drive/MyDrive/work2/Test/Key_Frames/1...,7
3,1,/content/drive/MyDrive/work2/Test/Key_Frames/1...,8
4,1,/content/drive/MyDrive/work2/Test/Key_Frames/1...,12

In [ ]:
import os
import pandas as pd
import speech_recognition as sr
from pydub import AudioSegment

def get_audio_length(file_path):
    """Return the rounded length of the audio file in seconds."""
    audio = AudioSegment.from_file(file_path)
    return int(len(audio) / 1000)  # Convert milliseconds to seconds and round down

def transcribe_audio_speech_recognition(audio_file_path):
    """Transcribe the given local audio file using the speech_recognition library."""
    recognizer = sr.Recognizer()
    with sr.AudioFile(audio_file_path) as source:
        audio_data = recognizer.record(source)
        try:
            return recognizer.recognize_google(audio_data, language="ur-PK")
        except sr.UnknownValueError:
            print("Google Speech Recognition could not understand the audio")
            return None
        except sr.RequestError as e:
            print(f"Could not request results from Google Speech Recognition service; {e}")
            return None

def read_words_from_file(file_path):
    """Read words from a file and return them as a list."""
    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            return [line.strip().lower() for line in file.readlines()]
    except FileNotFoundError:
        print(f"File not found: {file_path}")
        return []
    except Exception as e:
        print(f"Error reading file {file_path}: {e}")
        return []

def analyze_sentiment(words_in_transcript, negative_words, positive_words, length_in_seconds):
    negative_count, positive_count = 0, 0
    negative_positions, positive_positions = [], []
    for index, word in enumerate(words_in_transcript):
        position = (index + 1) // (len(words_in_transcript) / length_in_seconds)
        if word.lower() in negative_words:
            negative_count += 1
            negative_positions.append(round(position))
        elif word.lower() in positive_words:
            positive_count += 1
            positive_positions.append(round(position))
    return negative_count, positive_count, negative_positions, positive_positions

# Path to the folder containing audio files
audio_folder_path = '/content/drive/MyDrive/work2/Test/Audio'
negative_words = read_words_from_file('/content/drive/MyDrive/work2/dictionary/urdu_negative_words.txt')
positive_words = read_words_from_file('/content/drive/MyDrive/work2/dictionary/urdu_positive_words.txt')

results = []
for audio_file in os.listdir(audio_folder_path):
    if audio_file.endswith('.wav'):
        audio_file_path = os.path.join(audio_folder_path, audio_file)
        length_in_seconds = get_audio_length(audio_file_path)
        transcript = transcribe_audio_speech_recognition(audio_file_path)

        if transcript:
            words_in_transcript = transcript.split()
            negative_count, positive_count, negative_positions, positive_positions = analyze_sentiment(words_in_transcript, negative_words, positive_words, length_in_seconds)

            results.append({
                'File': audio_file,
                'Transcription': transcript,
                'Status': 'Transcribed',
                'Length': length_in_seconds,
                'WordCount': len(words_in_transcript),
                'negative_count': negative_count,
                'positive_count': positive_count,
                'negative_positions': negative_positions,
                'positive_positions': positive_positions
            })
        else:
            results.append({
                'File': audio_file,
                'Transcription': '',
                'Status': 'Not Transcribed',
                'Length': length_in_seconds,
                'WordCount': 0,
                'negative_count': 0,
                'positive_count': 0,
                'negative_positions': [],
                'positive_positions': []
            })

# Save results to a CSV file
csv_file_path = '/content/drive/MyDrive/work2/Test/key_positions_result.csv'
df = pd.DataFrame(results)
df.to_csv(csv_file_path, index=False)
print(f"Results saved to {csv_file_path}")

Results saved to /content/drive/MyDrive/work2/Test/key_positions_result.csv

In [ ]:

import pandas as pd

csv_file_path = '/content/drive/MyDrive/work2/Test/key_positions_result.csv'

df = pd.read_csv(csv_file_path)
df.head()

,File,Transcription,Status,Length,WordCount,negative_count,positive_count,negative_positions,positive_positions
0,1.wav,ٹینشن پاور ہے یعنی پڑھتے وقت وہ جتنا اپنے اندر...,Transcribed,164,561,35,9,"[6, 7, 8, 14, 21, 25, 28, 32, 37, 46, 48, 61, ...","[0, 8, 12, 14, 53, 95, 105, 113, 152]"

In [17]:
import os
import pandas as pd
import cv2

def extract_frames(video_file_path, times_in_seconds, output_folder):
    """Extract frames at specified times and save them to the output folder."""
    video_name = os.path.basename(video_file_path).split('.')[0]
    cap = cv2.VideoCapture(video_file_path)
    frame_info = []
    extracted_times = set()
    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break
        current_time = int(cap.get(cv2.CAP_PROP_POS_MSEC) // 1000)
        if current_time in times_in_seconds and current_time not in extracted_times:
            frame_filename = os.path.join(output_folder, f'{video_name}_frame_{current_time}.jpg')
            cv2.imwrite(frame_filename, frame)
            frame_info.append({'Video Name': video_name, 'Frame Path': frame_filename, 'Time in Seconds': current_time})
            extracted_times.add(current_time)
    cap.release()
    return frame_info

# Paths
video_directory = '/content/drive/MyDrive/work2/Test/Video'
key_positions_csv_path = '/content/drive/MyDrive/work2/Test/key_positions_result.csv'
output_base_folder = '/content/drive/MyDrive/work2/Test/Key_Frames'

# Create the output base folder if it doesn't exist
os.makedirs(output_base_folder, exist_ok=True)

# Load key positions from the CSV file
df = pd.read_csv(key_positions_csv_path)

all_frame_info = []  # Store info for all frames from all videos

# Process each video file based on key positions
for _, row in df.iterrows():
    video_name = os.path.splitext(row['File'])[0]
    negative_positions = eval(row['negative_positions'])
    positive_positions = eval(row['positive_positions'])
    key_positions = list(set(negative_positions + positive_positions))

    video_file_path = os.path.join(video_directory, f'{video_name}.mp4')

    if not os.path.exists(video_file_path):
        print(f"Video file not found: {video_file_path}")
        continue

    # Create output folder for this video
    output_folder = os.path.join(output_base_folder, video_name)
    os.makedirs(output_folder, exist_ok=True)

    # Extract frames at key positions
    frame_info = extract_frames(video_file_path, key_positions, output_folder)
    all_frame_info.extend(frame_info)

# Save frame information to a new CSV file
frames_csv_path = '/content/drive/MyDrive/work2/Test/Extracted_Key_Frames_Info.csv'
frame_info_df = pd.DataFrame(all_frame_info)
frame_info_df.to_csv(frames_csv_path, index=False)

print("Key frames extracted and saved.")
print(f"Frame information saved to {frames_csv_path}")

Key frames extracted and saved.
Frame information saved to /content/drive/MyDrive/work2/Test/Extracted_Key_Frames_Info.csv

In [18]:

import pandas as pd

csv_file_path = '/content/drive/MyDrive/work2/Test/Extracted_Key_Frames_Info.csv'

df = pd.read_csv(csv_file_path)
df.head()

,Video Name,Frame Path,Time in Seconds
0,1,/content/drive/MyDrive/work2/Test/Key_Frames/1...,0
1,1,/content/drive/MyDrive/work2/Test/Key_Frames/1...,6
2,1,/content/drive/MyDrive/work2/Test/Key_Frames/1...,7
3,1,/content/drive/MyDrive/work2/Test/Key_Frames/1...,8
4,1,/content/drive/MyDrive/work2/Test/Key_Frames/1...,12

In [34]:
import pandas as pd
import ast

# Paths to the CSV files
all_frames_info_path = '/content/drive/MyDrive/work2/Test/Extracted_All_Frames_Path.csv'
key_positions_info_path = '/content/drive/MyDrive/work2/Test/key_positions_result.csv'
output_csv_path = '/content/drive/MyDrive/work2/Test/Updated_Key_Frames_Info.csv'

# Load all frames information and key positions information
df_all_frames = pd.read_csv(all_frames_info_path)
df_key_positions = pd.read_csv(key_positions_info_path)

# Initialize the new column
df_all_frames['Key_Frame'] = 'N'

# Strip the common path prefix from the 'Frame Path' column in all frames
all_frames_prefix = '/content/drive/MyDrive/work2/Test/All_Frames'
df_all_frames['Frame Path'] = df_all_frames['Frame Path'].str.replace(all_frames_prefix, '', regex=False)

# Update key frame status based on key positions
for _, row in df_key_positions.iterrows():
    video_name = row['File'].split('.')[0]  # Assuming the 'File' column contains filenames like '1.wav'
    negative_positions = ast.literal_eval(row['negative_positions'])
    positive_positions = ast.literal_eval(row['positive_positions'])

    key_positions = set(negative_positions + positive_positions)

    # Update the 'Key_Frame' column to 'Y' if the frame time in seconds is found in the key positions
    df_all_frames.loc[(df_all_frames['Video Name'] == int(video_name)) & (df_all_frames['Time in Seconds'].isin(key_positions)), 'Key_Frame'] = 'Y'

# Add the prefix back to the 'Frame Path' column in all frames
df_all_frames['Frame Path'] = all_frames_prefix + df_all_frames['Frame Path']

# Save the updated dataframe to the CSV file
df_all_frames.to_csv(output_csv_path, index=False)
print("Frame information updated with 'Key_Frame' set to 'Y' for matching positions.")
print(f"Updated frame information saved to {output_csv_path}")

Frame information updated with 'Key_Frame' set to 'Y' for matching positions.
Updated frame information saved to /content/drive/MyDrive/work2/Test/Updated_Key_Frames_Info.csv

In [35]:

import pandas as pd

csv_file_path = '/content/drive/MyDrive/work2/Test/Updated_Key_Frames_Info.csv'

df = pd.read_csv(csv_file_path)
df.head(100)

,Video Name,Frame Path,Time in Seconds,Key_Frame
0,1,/content/drive/MyDrive/work2/Test/All_Frames/1...,0,Y
1,1,/content/drive/MyDrive/work2/Test/All_Frames/1...,1,N
2,1,/content/drive/MyDrive/work2/Test/All_Frames/1...,2,N
3,1,/content/drive/MyDrive/work2/Test/All_Frames/1...,3,N
4,1,/content/drive/MyDrive/work2/Test/All_Frames/1...,4,N
...,...,...,...,...
95,1,/content/drive/MyDrive/work2/Test/All_Frames/1...,95,Y
96,1,/content/drive/MyDrive/work2/Test/All_Frames/1...,96,N
97,1,/content/drive/MyDrive/work2/Test/All_Frames/1...,97,N
98,1,/content/drive/MyDrive/work2/Test/All_Frames/1...,98,Y
99,1,/content/drive/MyDrive/work2/Test/All_Frames/1...,99,Y

In [ ]:
import cv2
import pandas as pd
from fer import FER
import math
import os

def analyze_video(video_path):
    cap = cv2.VideoCapture(video_path)
    length = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    fps = cap.get(cv2.CAP_PROP_FPS)
    duration = length / fps  # Duration of the video in seconds
    rounded_duration = math.floor(duration)  # Round off the duration

    detector = FER(mtcnn=True)
    positive_count, negative_count, neutral_count = 0, 0, 0

    for i in range(rounded_duration):
        cap.set(cv2.CAP_PROP_POS_FRAMES, int(i * fps))  # Jump to the frame
        ret, frame = cap.read()
        if not ret:
            break
        emotions = detector.detect_emotions(frame)
        if emotions:
            largest_face = max(emotions, key=lambda x: x['box'][2] * x['box'][3])
            emotion = max(largest_face['emotions'], key=largest_face['emotions'].get)

            if emotion in ['happy', 'surprise']:
                positive_count += 1
            elif emotion in ['angry', 'fear', 'disgust']:
                negative_count += 1
            else:
                neutral_count += 1

    cap.release()
    return rounded_duration, positive_count, negative_count, neutral_count

# Load transcription results DataFrame
df = pd.read_csv('/content/drive/MyDrive/work2/Test/key_positions_result.csv')

# Initialize new columns
df['Total Frame Count'] = 0
df['Total Positive Frames'] = 0
df['Total Negative Frames'] = 0
df['Total Neutral Frames'] = 0
df['General Percentage'] = [(0, 0.0) for _ in range(len(df))]

# Directory containing videos
video_directory = '/content/drive/MyDrive/work2/Test/Video'

# Analyze each video
for index, row in df.iterrows():
    audio_name = row['File']
    video_name = audio_name.replace('.wav', '.mp4')
    video_path = os.path.join(video_directory, video_name)

    if os.path.exists(video_path):
        duration, pos_count, neg_count, neu_count = analyze_video(video_path)
        df.at[index, 'Total Frame Count'] = duration
        df.at[index, 'Total Positive Frames'] = pos_count
        df.at[index, 'Total Negative Frames'] = neg_count
        df.at[index, 'Total Neutral Frames'] = neu_count
        max_count = max(pos_count, neg_count, neu_count)

        general_percentage = (max_count / duration) * 100 if duration != 0 else 0
        sentiment = 1 if max_count == pos_count else 2 if max_count == neg_count else 0
        df.at[index, 'General Percentage'] = (sentiment, general_percentage)
    else:
        print(f"Error: Video file not found for {audio_name}")

# Save updated transcription results with video analysis
updated_csv_path = '/content/drive/MyDrive/work2/Test/Frames_meta_data.csv'
df.to_csv(updated_csv_path, index=False)
print(f"Transcription results with video analysis saved to {updated_csv_path}")

Transcription results with video analysis saved to /content/drive/MyDrive/work2/Test/Frames_meta_data.csv

In [27]:
import pandas as pd

csv_file_path = '/content/drive/MyDrive/work2/Test/Frames_meta_data.csv'

df = pd.read_csv(csv_file_path)
df.head()

,File,Transcription,Status,Length,WordCount,negative_count,positive_count,negative_positions,positive_positions,Total Frame Count,Total Positive Frames,Total Negative Frames,Total Neutral Frames,General Percentage
0,1.wav,ٹینشن پاور ہے یعنی پڑھتے وقت وہ جتنا اپنے اندر...,Transcribed,164,561,35,9,"[6, 7, 8, 14, 21, 25, 28, 32, 37, 46, 48, 61, ...","[0, 8, 12, 14, 53, 95, 105, 113, 152]",164,8,22,120,"(0, 73.17073170731707)"

In [ ]:
import cv2
import pandas as pd
from fer import FER
import math
import os

def analyze_video(video_path):
    cap = cv2.VideoCapture(video_path)
    length = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    fps = cap.get(cv2.CAP_PROP_FPS)
    duration = length / fps  # Duration of the video in seconds
    rounded_duration = math.floor(duration)  # Round off the duration

    detector = FER(mtcnn=True)
    positive_count, negative_count, neutral_count = 0, 0, 0

    for i in range(rounded_duration):
        cap.set(cv2.CAP_PROP_POS_FRAMES, int(i * fps))  # Jump to the frame
        ret, frame = cap.read()
        if not ret:
            break
        emotions = detector.detect_emotions(frame)
        if emotions:
            largest_face = max(emotions, key=lambda x: x['box'][2] * x['box'][3])
            emotion = max(largest_face['emotions'], key=largest_face['emotions'].get)

            if emotion in ['happy', 'surprise']:
                positive_count += 1
            elif emotion in ['angry', 'fear', 'disgust']:
                negative_count += 1
            else:
                neutral_count += 1

    cap.release()
    return rounded_duration, positive_count, negative_count, neutral_count

# Load transcription results DataFrame
df = pd.read_csv('/content/drive/MyDrive/work2/Test/key_positions_result.csv')

# Initialize new columns
df['Total Frame Count'] = 0
df['Total Positive Frames'] = 0
df['Total Negative Frames'] = 0
df['Total Neutral Frames'] = 0
df['General Percentage'] = [(0, 0.0) for _ in range(len(df))]

# Directory containing videos
video_directory = '/content/drive/MyDrive/work2/Test/Video/'

# Analyze each video
for index, row in df.iterrows():
    audio_name = row['File']
    video_name = audio_name.replace('.wav', '.mp4')
    video_path = os.path.join(video_directory, video_name)

    if os.path.exists(video_path):
        duration, pos_count, neg_count, neu_count = analyze_video(video_path)
        df.at[index, 'Total Frame Count'] = duration
        df.at[index, 'Total Positive Frames'] = pos_count
        df.at[index, 'Total Negative Frames'] = neg_count
        df.at[index, 'Total Neutral Frames'] = neu_count
        max_count = max(pos_count, neg_count, neu_count)

        general_percentage = (max_count / duration) * 100 if duration != 0 else 0
        sentiment = 1 if max_count == pos_count else 2 if max_count == neg_count else 0
        df.at[index, 'General Percentage'] = (sentiment, general_percentage)
    else:
        print(f"Error: Video file not found for {audio_name}")

# Save updated transcription results with video analysis
updated_csv_path = '/content/drive/MyDrive/work2/Test/Frames_meta_data.csv'
df.to_csv(updated_csv_path, index=False)
print(f"Transcription results with video analysis saved to {updated_csv_path}")

#Audio Model 1 (LSTM)

In [4]:
import librosa
import numpy as np
import tensorflow as tf
import pandas as pd

# Load the dataset
audio_df = pd.read_csv('/content/drive/MyDrive/work2/Test/Frames_meta_data.csv')

# Get the first audio file
first_audio_file = audio_df.iloc[0]['File']  # Changed index to 0

# Load the pre-trained model
audio_model_path = '/content/drive/MyDrive/work2/Final/Audio_Models/Audio_Model_1_LSTM.h5'
audio_model = tf.keras.models.load_model(audio_model_path)

# Helper function for audio feature extraction
def extract_features(file_path):
    y, sr = librosa.load(file_path, duration=3)
    mfccs = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=13)
    mel = librosa.feature.melspectrogram(y=y, sr=sr)
    contrast = librosa.feature.spectral_contrast(y=y, sr=sr)
    bandwidth = librosa.feature.spectral_bandwidth(y=y, sr=sr)
    energy_contour = librosa.feature.rms(y=y)
    spectral_rolloff = librosa.feature.spectral_rolloff(y=y, sr=sr)
    features = np.concatenate((
        np.mean(mfccs, axis=1),
        np.mean(mel, axis=1),
        np.mean(contrast, axis=1),
        np.mean(bandwidth, axis=1),
        np.mean(energy_contour, axis=1),
        np.mean(spectral_rolloff, axis=1)
    ))
    return features

# Predict audio sentiment
audio_path = f'/content/drive/MyDrive/work2/Test/Audio/{first_audio_file}'
audio_features = extract_features(audio_path)
audio_features_scaled = np.expand_dims(audio_features, axis=0)
audio_features_scaled = np.expand_dims(audio_features_scaled, -1)
audio_pred = audio_model.predict(audio_features_scaled)[0]
audio_sentiment = np.argmax(audio_pred)
audio_percentage = audio_pred[audio_sentiment]

# Save results to a DataFrame
results_df_audio1 = pd.DataFrame({
    'Modality': ['Audio Model 1'],
    'Sentiment': ['neutral' if audio_sentiment == 0 else 'positive' if audio_sentiment == 1 else 'negative'],
    'Percentage': [audio_percentage]
})

# Save to CSV for combining later
results_df_audio1.to_csv('/content/drive/MyDrive/work2/Test/Temp_Results/Temp_results_audio1.csv', index=False)
print("Results saved to /content/drive/MyDrive/work2/Test/Temp_Results/Temp_results_audio1.csv")

1/1 [==============================] - 1s 976ms/step
Results saved to /content/drive/MyDrive/work2/Test/Temp_Results/Temp_results_audio1.csv

#Audio Model 2 (Random Forest)

In [5]:
import librosa
import numpy as np
import pandas as pd
import joblib
import os

# Load the dataset
audio_df = pd.read_csv('/content/drive/MyDrive/work2/Test/Frames_meta_data.csv')

# Get the first audio file
first_audio_file = audio_df.iloc[0]['File']

# Load the pre-trained model
audio_model_path = '/content/drive/MyDrive/work2/Final/Audio_Models/Audio_Model_2_RandomForest.joblib'
audio_scaler_path = '/content/drive/MyDrive/work2/Final/Audio_Models/Audio_Model_2_RandomForest_Scaler.joblib'
audio_model = joblib.load(audio_model_path)
audio_scaler = joblib.load(audio_scaler_path)

# Helper function for audio feature extraction
def extract_features(file_path):
    y, sr = librosa.load(file_path, duration=3)
    mfccs = np.mean(librosa.feature.mfcc(y=y, sr=sr, n_mfcc=13), axis=1)
    chroma = np.mean(librosa.feature.chroma_stft(y=y, sr=sr), axis=1)
    mel = np.mean(librosa.feature.melspectrogram(y=y, sr=sr), axis=1)
    spectral_contrast = np.mean(librosa.feature.spectral_contrast(y=y, sr=sr), axis=1)
    tonnetz = np.mean(librosa.feature.tonnetz(y=librosa.effects.harmonic(y), sr=sr), axis=1)
    features = np.concatenate((mfccs, chroma, mel, spectral_contrast, tonnetz))
    return features

# Predict audio sentiment
audio_path = f'/content/drive/MyDrive/work2/Test/Audio/{first_audio_file}'
audio_features = extract_features(audio_path)
audio_features_scaled = audio_scaler.transform([audio_features])
audio_pred = audio_model.predict_proba(audio_features_scaled)[0]
audio_sentiment = np.argmax(audio_pred)
audio_percentage = audio_pred[audio_sentiment]

# Save results to a DataFrame
results_df_audio2 = pd.DataFrame({
    'Modality': ['Audio Model 2'],
    'Sentiment': ['neutral' if audio_sentiment == 0 else 'positive' if audio_sentiment == 1 else 'negative'],
    'Percentage': [audio_percentage]
})

# Save to CSV for combining later
results_df_audio2.to_csv('/content/drive/MyDrive/work2/Test/Temp_Results/Temp_results_audio2.csv', index=False)
print("Results saved to /content/drive/MyDrive/work2/Test/Temp_Results/Temp_results_audio2.csv")

Results saved to /content/drive/MyDrive/work2/Test/Temp_Results/Temp_results_audio2.csv

#Text Model 1 (BERT)

In [13]:
import torch
from transformers import BertTokenizer, BertForSequenceClassification
from torch.utils.data import DataLoader, SequentialSampler, TensorDataset
import numpy as np
import pandas as pd

# Load the dataset
text_df = pd.read_csv('/content/drive/MyDrive/work2/Test/Frames_meta_data.csv')

# Get the first text transcription
first_text = text_df.iloc[0]['Transcription']

# Load the pre-trained model and tokenizer
tokenizer = BertTokenizer.from_pretrained('/content/drive/MyDrive/work2/Final/Text_Work/Text_model_1_BERT_Model')
model = BertForSequenceClassification.from_pretrained('/content/drive/MyDrive/work2/Final/Text_Work/Text_model_1_BERT_Model')

# Tokenize and encode the text
encoded_dict = tokenizer.encode_plus(
    first_text,
    add_special_tokens=True,
    max_length=64,
    truncation=True,
    padding='max_length',
    return_attention_mask=True,
    return_tensors='pt'
)

input_ids = encoded_dict['input_ids']
attention_mask = encoded_dict['attention_mask']

# Create DataLoader
dataset = TensorDataset(input_ids, attention_mask)
dataloader = DataLoader(dataset, sampler=SequentialSampler(dataset), batch_size=1)

# Predict text sentiment
model.eval()
with torch.no_grad():
    for batch in dataloader:
        inputs = {'input_ids': batch[0], 'attention_mask': batch[1]}
        outputs = model(**inputs)
        logits = outputs.logits
        preds = torch.softmax(logits, dim=1).cpu().numpy()

text_sentiment = np.argmax(preds)
text_percentage = preds[0][text_sentiment]

# Save results to a DataFrame
results_df_text1 = pd.DataFrame({
    'Modality': ['Text Model 1'],
    'Sentiment': ['neutral' if text_sentiment == 0 else 'positive' if text_sentiment == 1 else 'negative'],
    'Percentage': [text_percentage]
})

# Save to CSV for combining later
results_df_text1.to_csv('/content/drive/MyDrive/work2/Test/Temp_Results/Temp_results_text1.csv', index=False)
print("Results saved to /content/drive/MyDrive/work2/Test/Temp_Results/Temp_results_text1.csv")

Results saved to /content/drive/MyDrive/work2/Test/Temp_Results/Temp_results_text1.csv

In [14]:
import pandas as pd

csv_file_path = '/content/drive/MyDrive/work2/Test/Temp_Results/Temp_results_text1.csv'

df = pd.read_csv(csv_file_path)
df.head()

       Modality Sentiment  Percentage
0  Text Model 1  negative    0.858028

#Text Model 2 (Logistic Regression)

In [12]:
import pandas as pd
import numpy as np
import re
import nltk
import joblib

# Load the dataset
text_df = pd.read_csv('/content/drive/MyDrive/work2/Test/Frames_meta_data.csv')

# Get the first text transcription
first_text = text_df.iloc[0]['Transcription']

# Function to remove unwanted characters
def removing_unwanted_data(text):
    text = re.sub(r'https?:\/\/.*[\r\n]*', '', text, flags=re.MULTILINE)
    text = re.sub(r'\<a href', ' ', text)
    text = re.sub(r'&amp;', ' ', text)
    text = re.sub(r'[_"\-;%()|+&=*%.,!?:#$@\[\]/]', ' ', text)
    text = re.sub(r'<br />', ' ', text)
    text = re.sub(r'\'', ' ', text)
    text = nltk.WordPunctTokenizer().tokenize(text)
    return text

# Apply preprocessing
cleaned_text = removing_unwanted_data(first_text)

# Redefine custom tokenizer function
def custom_tokenizer(doc):
    return doc

# Load the saved vectorizer and model
vectorizer_path = '/content/drive/MyDrive/work2/Final/Text_Work/Text_Models_2_and_3/Text_model_2_bow_vectorizer.pkl'
model_path = '/content/drive/MyDrive/work2/Final/Text_Work/Text_Models_2_and_3/Text_model_2_logistic_regression_bow.pkl'
vectorizer = joblib.load(vectorizer_path)
model = joblib.load(model_path)

# Transform the data using the loaded vectorizer
X = vectorizer.transform([' '.join(cleaned_text)])

# Predict text sentiment
text_pred = model.predict_proba(X)[0]
text_sentiment = np.argmax(text_pred)
text_percentage = text_pred[text_sentiment]

# Save results to a DataFrame
results_df_text2 = pd.DataFrame({
    'Modality': ['Text Model 2'],
    'Sentiment': ['neutral' if text_sentiment == 0 else 'positive' if text_sentiment == 1 else 'negative'],
    'Percentage': [text_percentage]
})

# Save to CSV for combining later
results_df_text2.to_csv('/content/drive/MyDrive/work2/Test/Temp_Results/Temp_results_text2.csv', index=False)
print("Results saved to /content/drive/MyDrive/work2/Test/Temp_Results/Temp_results_text2.csv")

Results saved to /content/drive/MyDrive/work2/Test/Temp_Results/Temp_results_text2.csv

In [16]:
import pandas as pd

csv_file_path = '/content/drive/MyDrive/work2/Test/Temp_Results/Temp_results_text2.csv'

df = pd.read_csv(csv_file_path)
df.head()

       Modality Sentiment  Percentage
0  Text Model 2  negative         1.0

#Video Model 1 (MobileNetV2)

In [38]:
import os
import numpy as np
import pandas as pd
import cv2
import tensorflow as tf
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

# Load the datasets
frames_df = pd.read_csv('/content/drive/MyDrive/work2/Test/Updated_Key_Frames_Info.csv')
video_folder_path = '/content/drive/MyDrive/work2/Test/Video'

# Get the list of video files
video_files = [f for f in os.listdir(video_folder_path) if f.endswith('.mp4')]

# Process each video
results = []

# Helper function for video feature extraction
def preprocess_image(filepath):
    img = cv2.imread(filepath)
    if img is None:
        print(f"Failed to read image: {filepath}")
        return None
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = cv2.resize(img, (224, 224))
    img = preprocess_input(img)
    return img

# Load the pre-trained model
video_model_path = '/content/drive/MyDrive/work2/Final/Image_Models/Video_Model_1_CNN_with_MobileNetV2.h5'
video_model = tf.keras.models.load_model(video_model_path)

for video_file in video_files:
    video_name = video_file.replace('.mp4', '')

    # Get the frames corresponding to the current video and key frames only
    video_frames = frames_df[(frames_df['Video Name'].astype(str) == video_name) & (frames_df['Key_Frame'] == 'Y')]

    predictions = []
    for frame_path in video_frames['Frame Path']:
        frame_full_path = os.path.join(all_frames_prefix, frame_path)  # Add the prefix back
        video_image = preprocess_image(frame_full_path)
        if video_image is not None:
            video_image = np.expand_dims(video_image, axis=0)
            video_pred = video_model.predict(video_image)[0]
            predictions.append(video_pred)

    if predictions:
        # Average predictions
        average_pred = np.mean(predictions, axis=0)
        video_sentiment = np.argmax(average_pred)
        video_percentage = average_pred[video_sentiment]

        results.append({
            'Modality': 'Video Model 1',
            'Sentiment': 'neutral' if video_sentiment == 0 else 'positive' if video_sentiment == 1 else 'negative',
            'Percentage': video_percentage
        })
    else:
        results.append({
            'Modality': 'Video Model 1',
            'Sentiment': 'N/A',
            'Percentage': 0.0
        })

# Save results to a DataFrame
results_df = pd.DataFrame(results)

# Save to CSV for combining later
results_csv_path = '/content/drive/MyDrive/work2/Test/Temp_Results/Temp_results_video1.csv'
results_df.to_csv(results_csv_path, index=False)
print(f"Results saved to {results_csv_path}")

1/1 [==============================] - 2s 2s/step
1/1 [==============================] - 0s 85ms/step
1/1 [==============================] - 0s 86ms/step
1/1 [==============================] - 0s 151ms/step
1/1 [==============================] - 0s 54ms/step
1/1 [==============================] - 0s 60ms/step
1/1 [==============================] - 0s 59ms/step
1/1 [==============================] - 0s 60ms/step
1/1 [==============================] - 0s 52ms/step
1/1 [==============================] - 0s 72ms/step
1/1 [==============================] - 0s 61ms/step
1/1 [==============================] - 0s 52ms/step
1/1 [==============================] - 0s 57ms/step
1/1 [==============================] - 0s 57ms/step
1/1 [==============================] - 0s 58ms/step
1/1 [==============================] - 0s 52ms/step
1/1 [==============================] - 0s 78ms/step
1/1 [==============================] - 0s 53ms/step
1/1 [==============================] - 0s 56ms/step
1/1 [==============================] - 0s 59ms/step
1/1 [==============================] - 0s 62ms/step
1/1 [==============================] - 0s 58ms/step
1/1 [==============================] - 0s 54ms/step
1/1 [==============================] - 0s 58ms/step
1/1 [==============================] - 0s 55ms/step
1/1 [==============================] - 0s 54ms/step
1/1 [==============================] - 0s 55ms/step
1/1 [==============================] - 0s 52ms/step
1/1 [==============================] - 0s 53ms/step
1/1 [==============================] - 0s 57ms/step
1/1 [==============================] - 0s 57ms/step
1/1 [==============================] - 0s 53ms/step
1/1 [==============================] - 0s 55ms/step
1/1 [==============================] - 0s 54ms/step
1/1 [==============================] - 0s 54ms/step
1/1 [==============================] - 0s 53ms/step
1/1 [==============================] - 0s 65ms/step
1/1 [==============================] - 0s 54ms/step
Results saved to /content/drive/MyDrive/work2/Test/Temp_Results/Temp_results_video1.csv

In [39]:
import pandas as pd

csv_file_path = '/content/drive/MyDrive/work2/Test/Temp_Results/Temp_results_video1.csv'

df = pd.read_csv(csv_file_path)
df.head()

        Modality Sentiment  Percentage
0  Video Model 1  negative    0.380225

#Video Model 2 (Video_Model_2_random_forest_model)

In [42]:
import os
import numpy as np
import pandas as pd
import cv2
import joblib
from skimage.feature import hog

# Load the datasets
frames_df = pd.read_csv('/content/drive/MyDrive/work2/Test/Updated_Key_Frames_Info.csv')
video_folder_path = '/content/drive/MyDrive/work2/Test/Video'

# Get the list of video files
video_files = [f for f in os.listdir(video_folder_path) if f.endswith('.mp4')]

# Helper function for video feature extraction using HOG
def preprocess_image_hog(filepath):
    img = cv2.imread(filepath)
    if img is None:
        print(f"Failed to read image: {filepath}")
        return None
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img = cv2.resize(img, (128, 128))
    hog_features = hog(img, pixels_per_cell=(8, 8), cells_per_block=(2, 2), block_norm='L2-Hys')
    return hog_features

# Load the pre-trained model
video_model_path_rf = '/content/drive/MyDrive/work2/Final/Image_Models/Video_Model_2_random_forest_model.pkl'
video_model_rf = joblib.load(video_model_path_rf)

# Process each video
results = []

for video_file in video_files:
    video_name = video_file.replace('.mp4', '')

    # Get the frames corresponding to the current video and key frames only
    video_frames = frames_df[(frames_df['Video Name'].astype(str) == video_name) & (frames_df['Key_Frame'] == 'Y')]

    predictions_rf = []

    for frame_path in video_frames['Frame Path']:
        frame_full_path = os.path.join('/content/drive/MyDrive/work2/Test/All_Frames', frame_path)  # Add the prefix back

        # Predict with Random Forest model using HOG features
        video_features_hog = preprocess_image_hog(frame_full_path)
        if video_features_hog is not None:
            video_features_hog = video_features_hog.reshape(1, -1)
            video_pred_rf = video_model_rf.predict_proba(video_features_hog)[0]
            predictions_rf.append(video_pred_rf)

    if predictions_rf:
        # Average predictions for Random Forest model
        average_pred_rf = np.mean(predictions_rf, axis=0)
        video_sentiment_rf = np.argmax(average_pred_rf)
        video_percentage_rf = average_pred_rf[video_sentiment_rf]

        results.append({
            'Modality': 'Video Model 2',
            'Sentiment': 'neutral' if video_sentiment_rf == 0 else 'positive' if video_sentiment_rf == 1 else 'negative',
            'Percentage': video_percentage_rf
        })

# Save results to a DataFrame
results_df = pd.DataFrame(results)

# Save to CSV for combining later
results_csv_path = '/content/drive/MyDrive/work2/Test/Temp_Results/Temp_results_video2.csv'
results_df.to_csv(results_csv_path, index=False)
print(f"Results saved to {results_csv_path}")

Results saved to /content/drive/MyDrive/work2/Test/Temp_Results/Temp_results_video2.csv

In [43]:
import pandas as pd

csv_file_path = '/content/drive/MyDrive/work2/Test/Temp_Results/Temp_results_video2.csv'

df = pd.read_csv(csv_file_path)
df.head()

        Modality Sentiment  Percentage
0  Video Model 2  negative    0.389816

In [44]:
import os
import pandas as pd

# Load individual model results
results_audio1 = pd.read_csv('/content/drive/MyDrive/work2/Test/Temp_Results/Temp_results_audio1.csv')
results_audio2 = pd.read_csv('/content/drive/MyDrive/work2/Test/Temp_Results/Temp_results_audio2.csv')
results_text1 = pd.read_csv('/content/drive/MyDrive/work2/Test/Temp_Results/Temp_results_text1.csv')
results_text2 = pd.read_csv('/content/drive/MyDrive/work2/Test/Temp_Results/Temp_results_text2.csv')
results_video1 = pd.read_csv('/content/drive/MyDrive/work2/Test/Temp_Results/Temp_results_video1.csv')
results_video2 = pd.read_csv('/content/drive/MyDrive/work2/Test/Temp_Results/Temp_results_video2.csv')

# Define the path to the video folder
video_folder_path = '/content/drive/MyDrive/work2/Test/Video'

# Get the list of video files
video_files = [f for f in os.listdir(video_folder_path) if f.endswith('.mp4')]

# Iterate over each video file in the folder
for video_file in video_files:
    video_name = video_file.replace('.mp4', '')

    # Manually set the sentiment for the video (assuming sentiment '2' for demonstration)
    actual_senti = '2'

    # Define weights for each model
    weights = {
        'Audio Model 1': 0.529,
        'Audio Model 2': 0.521,
        'Text Model 1': 0.990,
        'Text Model 2': 0.986,
        'Video Model 1': 0.643,
        'Video Model 2': 0.653
    }

    # Phase 1: Fusion within each modality
    def fuse_modality_pair(model1, model2, weight1, weight2):
        combined = pd.concat([model1, model2], ignore_index=True)
        combined['Weighted Percentage'] = combined.apply(lambda row: row['Percentage'] * (weight1 if row['Modality'] == model1['Modality'].iloc[0] else weight2), axis=1)
        return combined.loc[combined['Weighted Percentage'].idxmax()]

    audio_result = fuse_modality_pair(results_audio1, results_audio2, weights['Audio Model 1'], weights['Audio Model 2'])
    text_result = fuse_modality_pair(results_text1, results_text2, weights['Text Model 1'], weights['Text Model 2'])
    video_result = fuse_modality_pair(results_video1, results_video2, weights['Video Model 1'], weights['Video Model 2'])

    # Combine results from all modalities
    phase1_results = pd.DataFrame([audio_result, text_result, video_result])

    print("Phase 1 Results (Fusion within each modality):")
    print(phase1_results[['Modality', 'Sentiment', 'Percentage', 'Weighted Percentage']])

    # Phase 2: Fusion across modalities
    max_predicted_sentiment = phase1_results.loc[phase1_results['Percentage'].idxmax()]
    max_sentiment = max_predicted_sentiment['Sentiment']
    max_percentage = max_predicted_sentiment['Percentage']
    max_weight = 0.33  # Adjust this weight as needed

    # Calculate Final Weighted Percentage
    phase1_results['Final Weighted Percentage'] = phase1_results.apply(
        lambda row: row['Weighted Percentage'] + (max_weight * max_percentage if str(row['Sentiment']) == str(max_sentiment) else 0),
        axis=1
    )

    # Determine the final sentiment
    final_sentiment = phase1_results.loc[phase1_results['Final Weighted Percentage'].idxmax()]

    print("\nFinal Ensemble Sentiment Result:")
    print(final_sentiment)

    # Save the final result to a CSV file
    final_result_df = pd.DataFrame({
        'File': [video_file],
        'Actual Senti': [actual_senti],
        'Predicted Sentiment': [final_sentiment['Sentiment']],
        'Weighted Percentage': [final_sentiment['Final Weighted Percentage']],
        'Modality': [final_sentiment['Modality']],
        'Percentage': [final_sentiment['Percentage']]
    })

    # Define the path to the CSV file
    csv_file_path = '/content/drive/MyDrive/work2/Test/Final_Evaluation_Ensemble_Result.csv'

    # Check if the file exists and save accordingly
    if not os.path.exists(csv_file_path):
        final_result_df.to_csv(csv_file_path, index=False)
    else:
        final_result_df.to_csv(csv_file_path, mode='a', header=False, index=False)

    print(f"Final ensemble result for {video_file} saved to {csv_file_path}")

Phase 1 Results (Fusion within each modality):
        Modality Sentiment  Percentage  Weighted Percentage
1  Audio Model 2  positive    0.440000              0.22924
1   Text Model 2  negative    1.000000              0.98600
1  Video Model 2  negative    0.389816              0.25455

Final Ensemble Sentiment Result:
        Modality Sentiment  Percentage  Weighted Percentage  \
1  Audio Model 2  positive    0.440000              0.22924
1   Text Model 2  negative    1.000000              0.98600
1  Video Model 2  negative    0.389816              0.25455

   Final Weighted Percentage
1                    0.22924
1                    0.98600
1                    0.25455
Final ensemble result for 1.mp4 saved to /content/drive/MyDrive/work2/Test/Final_Evaluation_Ensemble_Result.csv